### ISSUE TITLE
otel-collector panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ksponomarev** [SigNoz/signoz#1453]
## Bug description
Hello
opentelemetry-collector can't run because of error

## Expected behavior
```bash
2022-07-27T11:46:33.354Z	info	service/collector.go:124	Everything is ready. Begin running and processing data.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1063552]

goroutine 137 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhousemetricsexporter.(*PrwExporter).export.func1()
	/src/exporter/clickhousemetricsexporter/exporter.go:279 +0xf2
created by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhousemetricsexporter.(*PrwExporter).export
	/src/exporter/clickhousemetricsexporter/exporter.go:275 +0x256
```

## How to reproduce

1. [values.yaml](https://gist.github.com/ksponomarev/51cbedc57dcb395786097d88cb6c517e)
2. helm upgrade -i signoz signoz/signoz -f values.yaml

## Version information 
- frontend version: '0.10.0'
- query-service version: '0.10.0'
- alertmanager version: '0.23.0-0.1'
- otel-collector version: '0.45.1-1.0'
- otel-collector-metrics version: '0.45.1-1.0'
- Chart version: 0.2.0
- Chart appVersion: 0.10.0

**Comment by srikanthccv** [comment]
Can you confirm if the ClickHouse server is running and reachable when you run into this issue?

**Comment by ksponomarev** [comment]
```bash
$ nc -vz clickhouse.example.com 9000
Connection to clickhouse.example.com (10.244.34.132) 9000 port [tcp/*] succeeded!
$ nc -vz clickhouse.example.com 8123
Connection to clickhouse.example.com (10.244.34.132) 8123 port [tcp/*] succeeded!
```

**Comment by srikanthccv** [comment]
Is it the same ClickHouse configured to be used by collector?

**Comment by ksponomarev** [comment]
yes. Clickhouse was configured for all services

**Comment by srikanthccv** [comment]
Can you share the full log of the collector startup to crash?

**Comment by ksponomarev** [comment]
```log
2022/07/27 13:02:11 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/07/27 13:02:11 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
2022-07-27T13:02:11.838Z	info	clickhousetracesexporter/clickhouse_factory.go:82	Running migrations from path: 	{"kind": "exporter", "name": "clickhousetraces", "test": "/migrations"}
2022-07-27T13:02:11.865Z	info	clickhousetracesexporter/clickhouse_factory.go:94	Clickhouse Migrate finished	{"kind": "exporter", "name": "clickhousetraces", "error": "Dirty database version 6. Fix and force version."}
2022-07-27T13:02:11.865Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "clickhousetraces"}
time="2022-07-27T13:02:11Z" level=info msg="Executing:\nCREATE DATABASE IF NOT EXISTS signoz_metrics\n" component=clickhouse
time="2022-07-27T13:02:11Z" level=info msg="Executing:\nCREATE TABLE IF NOT EXISTS signoz_metrics.samples_v2 (\n\t\t\tmetric_name LowCardinality(String),\n\t\t\tfingerprint UInt64 Codec(DoubleDelta, LZ4),\n\t\t\ttimestamp_ms Int64 Codec(DoubleDelta, LZ4),\n\t\t\tvalue Float64 Codec(Gorilla, LZ4)\n\t\t)\n\t\tENGINE = MergeTree\n\t\t\tPARTITION BY toDate(timestamp_ms / 1000)\n\t\t\tORDER BY (metric_name, fingerprint, timestamp_ms)\n" component=clickhouse
time="2022-07-27T13:02:11Z" level=info msg="Executing:\nSET allow_experimental_object_type = 1\n" component=clickhouse
2022-07-27T13:02:11.879Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "clickhousemetricswrite"}
2022-07-27T13:02:11.879Z	info	builder/exporters_builder.go:255	Exporter was built.	{"kind": "exporter", "name": "prometheus"}
2022-07-27T13:02:11.879Z	info	builder/pipelines_builder.go:223	Pipeline was built.	{"name": "pipeline", "name": "metrics/spanmetrics"}
2022-07-27T13:02:11.879Z	info	signozspanmetricsprocessor/processor.go:105	Building signozspanmetricsprocessor	{"kind": "processor", "name": "signozspanmetrics/prometheus"}
2022-07-27T13:02:11.879Z	info	builder/pipelines_builder.go:223	Pipeline was built.	{"name": "pipeline", "name": "traces"}
2022-07-27T13:02:11.880Z	info	builder/pipelines_builder.go:223	Pipeline was built.	{"name": "pipeline", "name": "metrics"}
2022-07-27T13:02:11.880Z	info	builder/receivers_builder.go:226	Receiver was built.	{"kind": "receiver", "name": "hostmetrics", "datatype": "metrics"}
2022-07-27T13:02:11.880Z	info	builder/receivers_builder.go:226	Receiver was built.	{"kind": "receiver", "name": "otlp/spanmetrics", "datatype": "metrics"}
2022-07-27T13:02:11.880Z	info	builder/receivers_builder.go:226	Receiver was built.	{"kind": "receiver", "name": "otlp", "datatype": "metrics"}
2022-07-27T13:02:11.880Z	info	builder/receivers_builder.go:226	Receiver was built.	{"kind": "receiver", "name": "otlp", "datatype": "traces"}
2022-07-27T13:02:11.880Z	info	builder/receivers_builder.go:226	Receiver was built.	{"kind": "receiver", "name": "jaeger", "datatype": "traces"}
2022-07-27T13:02:11.880Z	info	service/service.go:82	Starting extensions...
2022-07-27T13:02:11.880Z	info	extensions/extensions.go:38	Extension is starting...	{"kind": "extension", "name": "health_check"}
2022-07-27T13:02:11.880Z	info	healthcheckextension/healthcheckextension.go:44	Starting health_check extension	{"kind": "extension", "name": "health_check", "config": {"Port":0,"TCPAddr":{"Endpoint":"0.0.0.0:13133"},"Path":"/","CheckCollectorPipeline":{"Enabled":false,"Interval":"5m","ExporterFailureThreshold":5}}}
2022-07-27T13:02:11.894Z	info	extensions/extensions.go:42	Extension started.	{"kind": "extension", "name": "health_check"}
2022-07-27T13:02:11.894Z	info	extensions/extensions.go:38	Extension is starting...	{"kind": "extension", "name": "zpages"}
2022-07-27T13:02:11.894Z	info	zpagesextension/zpagesextension.go:40	Register Host's zPages	{"kind": "extension", "name": "zpages"}
2022-07-27T13:02:11.899Z	info	zpagesextension/zpagesextension.go:53	Starting zPages extension	{"kind": "extension", "name": "zpages", "config": {"TCPAddr":{"Endpoint":"localhost:55679"}}}
2022-07-27T13:02:11.899Z	info	extensions/extensions.go:42	Extension started.	{"kind": "extension", "name": "zpages"}
2022-07-27T13:02:11.899Z	info	service/service.go:87	Starting exporters...
2022-07-27T13:02:11.899Z	info	builder/exporters_builder.go:40	Exporter is starting...	{"kind": "exporter", "name": "clickhousetraces"}
2022-07-27T13:02:11.899Z	info	builder/exporters_builder.go:48	Exporter started.	{"kind": "exporter", "name": "clickhousetraces"}
2022-07-27T13:02:11.900Z	info	builder/exporters_builder.go:40	Exporter is starting...	{"kind": "exporter", "name": "clickhousemetricswrite"}
2022-07-27T13:02:11.900Z	info	builder/exporters_builder.go:48	Exporter started.	{"kind": "exporter", "name": "clickhousemetricswrite"}
2022-07-27T13:02:11.900Z	info	builder/exporters_builder.go:40	Exporter is starting...	{"kind": "exporter", "name": "prometheus"}
2022-07-27T13:02:11.900Z	info	builder/exporters_builder.go:48	Exporter started.	{"kind": "exporter", "name": "prometheus"}
2022-07-27T13:02:11.900Z	info	service/service.go:92	Starting processors...
2022-07-27T13:02:11.900Z	info	builder/pipelines_builder.go:54	Pipeline is starting...	{"name": "pipeline", "name": "metrics/spanmetrics"}
2022-07-27T13:02:11.900Z	info	builder/pipelines_builder.go:65	Pipeline is started.	{"name": "pipeline", "name": "metrics/spanmetrics"}
2022-07-27T13:02:11.900Z	info	builder/pipelines_builder.go:54	Pipeline is starting...	{"name": "pipeline", "name": "traces"}
2022-07-27T13:02:11.900Z	info	signozspanmetricsprocessor/processor.go:238	Starting signozspanmetricsprocessor	{"kind": "processor", "name": "signozspanmetrics/prometheus"}
2022-07-27T13:02:11.900Z	debug	signozspanmetricsprocessor/processor.go:252	Looking for signozspanmetrics exporter from available exporters	{"kind": "processor", "name": "signozspanmetrics/prometheus", "signozspanmetrics-exporter": "prometheus", "available-exporters": ["clickhousemetricswrite"]}
2022-07-27T13:02:11.900Z	debug	signozspanmetricsprocessor/processor.go:252	Looking for signozspanmetrics exporter from available exporters	{"kind": "processor", "name": "signozspanmetrics/prometheus", "signozspanmetrics-exporter": "prometheus", "available-exporters": ["clickhousemetricswrite", "prometheus"]}
2022-07-27T13:02:11.900Z	info	signozspanmetricsprocessor/processor.go:258	Found exporter	{"kind": "processor", "name": "signozspanmetrics/prometheus", "signozspanmetrics-exporter": "prometheus"}
2022-07-27T13:02:11.900Z	info	signozspanmetricsprocessor/processor.go:266	Started signozspanmetricsprocessor	{"kind": "processor", "name": "signozspanmetrics/prometheus"}
2022-07-27T13:02:11.900Z	info	builder/pipelines_builder.go:65	Pipeline is started.	{"name": "pipeline", "name": "traces"}
2022-07-27T13:02:11.900Z	info	builder/pipelines_builder.go:54	Pipeline is starting...	{"name": "pipeline", "name": "metrics"}
2022-07-27T13:02:11.900Z	info	builder/pipelines_builder.go:65	Pipeline is started.	{"name": "pipeline", "name": "metrics"}
2022-07-27T13:02:11.900Z	info	service/service.go:97	Starting receivers...
2022-07-27T13:02:11.900Z	info	builder/receivers_builder.go:68	Receiver is starting...	{"kind": "receiver", "name": "hostmetrics"}
2022-07-27T13:02:11.903Z	info	builder/receivers_builder.go:73	Receiver started.	{"kind": "receiver", "name": "hostmetrics"}
2022-07-27T13:02:11.903Z	info	builder/receivers_builder.go:68	Receiver is starting...	{"kind": "receiver", "name": "otlp/spanmetrics"}
2022-07-27T13:02:11.903Z	info	otlpreceiver/otlp.go:69	Starting GRPC server on endpoint localhost:12345	{"kind": "receiver", "name": "otlp/spanmetrics"}
2022-07-27T13:02:11.909Z	info	builder/receivers_builder.go:73	Receiver started.	{"kind": "receiver", "name": "otlp/spanmetrics"}
2022-07-27T13:02:11.909Z	info	builder/receivers_builder.go:68	Receiver is starting...	{"kind": "receiver", "name": "otlp"}
2022-07-27T13:02:11.909Z	info	otlpreceiver/otlp.go:69	Starting GRPC server on endpoint 0.0.0.0:4317	{"kind": "receiver", "name": "otlp"}
2022-07-27T13:02:11.909Z	info	otlpreceiver/otlp.go:87	Starting HTTP server on endpoint 0.0.0.0:4318	{"kind": "receiver", "name": "otlp"}
2022-07-27T13:02:11.909Z	info	otlpreceiver/otlp.go:147	Setting up a second HTTP listener on legacy endpoint 0.0.0.0:55681	{"kind": "receiver", "name": "otlp"}
2022-07-27T13:02:11.909Z	info	otlpreceiver/otlp.go:87	Starting HTTP server on endpoint 0.0.0.0:55681	{"kind": "receiver", "name": "otlp"}
2022-07-27T13:02:11.909Z	info	builder/receivers_builder.go:73	Receiver started.	{"kind": "receiver", "name": "otlp"}
2022-07-27T13:02:11.909Z	info	builder/receivers_builder.go:68	Receiver is starting...	{"kind": "receiver", "name": "jaeger"}
2022-07-27T13:02:11.910Z	info	static/strategy_store.go:203	No sampling strategies provided or URL is unavailable, using defaults	{"kind": "receiver", "name": "jaeger"}
2022-07-27T13:02:11.910Z	info	builder/receivers_builder.go:73	Receiver started.	{"kind": "receiver", "name": "jaeger"}
2022-07-27T13:02:11.910Z	info	healthcheck/handler.go:129	Health Check state change	{"kind": "extension", "name": "health_check", "status": "ready"}
2022-07-27T13:02:11.910Z	info	service/telemetry.go:95	Setting up own telemetry...
2022-07-27T13:02:11.911Z	info	service/telemetry.go:115	Serving Prometheus metrics	{"address": ":8888", "level": "basic", "service.instance.id": "65e39168-ffd0-4afe-a6f6-a4284b9df236", "service.version": "latest"}
2022-07-27T13:02:11.911Z	info	service/collector.go:229	Starting otelcontribcol...	{"Version": "latest", "NumCPU": 8}
2022-07-27T13:02:11.911Z	info	service/collector.go:124	Everything is ready. Begin running and processing data.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1063552]

goroutine 195 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhousemetricsexporter.(*PrwExporter).export.func1()
	/src/exporter/clickhousemetricsexporter/exporter.go:279 +0xf2
created by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhousemetricsexporter.(*PrwExporter).export
	/src/exporter/clickhousemetricsexporter/exporter.go:275 +0x256
```

**Comment by srikanthccv** [comment]
Thanks. There is certainly something wrong here since the traces exporter migrations also were not successful.
```
2022-07-27T13:02:11.865Z	info	clickhousetracesexporter/clickhouse_factory.go:94	Clickhouse Migrate finished	{"kind": "exporter", "name": "clickhousetraces", "error": "Dirty database version 6. Fix and force version."}
```
And the mostly likely reason for this panic is that ClickHouse connection was established successfully. Are you sure the user credentials are correct and database is accessible with them?

**Comment by ksponomarev** [comment]
```bash
[root@pytest-6986d4d55d-rkvzb /]# clickhouse-client --ask-password --host clickhouse.example.com -u signoz
ClickHouse client version 20.8.3.18.
Password for user (signoz): 
Connecting to clickhouse.example.com:9000 as user signoz.
Connected to ClickHouse server version 20.8.3 revision 54438.

clickhouse.example.com :)
```
Yeah, I can connect to clickhouse. I also checked secret with clickhouse password and it's correct. 
Also checked envs in pod - the password is correct
I'll try to find information about db version. I missed this error because it was `info` type :(
Databases:
```bash
SHOW DATABASES

┌─name───────────────────────────┐
│ _temporary_and_external_tables │
│ default                        │
│ signoz_metrics                 │
│ signoz_traces                  │
│ system                         │
└────────────────────────────────┘
```

**Comment by ksponomarev** [comment]
version of clickhouse:
```bash
ClickHouse server version 20.8.3.18.
```

**Comment by srikanthccv** [comment]
Ok you have to use ClickHouse server version `22.4` or later when working with SigNoz version >= `0.9`.

**Comment by ksponomarev** [comment]
Sorry, didn't notice that in `values.yaml` and docs. 
I'll try to update and write results
Thank u

**Comment by ksponomarev** [comment]
Upgrade clickhouse version helped. Thank you. 
But there is a same error with migration FYI

**Comment by srikanthccv** [comment]
Is application running and showing data now? What is the environment you are running this on?

**Comment by ksponomarev** [comment]
Not yet. This is dev environment. App is running but there are some problems. Trying to find a problem. May be with connection between backend and frontend

**Comment by ksponomarev** [comment]
I'm back) Sorry, I had emergency tasks and had to drop signoz. Now, I deployed it and have a new problem
```bash
2022-08-03T07:56:40.071Z	DEBUG	clickhouseReader/reader.go:1074	Error in processing sql query: code: 60, message: Table signoz_traces.durationSortMV doesn't exist
2022-08-03T07:56:40.071Z	ERROR	app/http_handler.go:1835	HTTP handler, Internal Server Error{error 26 0  Error in processing sql query: code: 60, message: Table signoz_traces.durationSortMV doesn't exist}
go.signoz.io/query-service/app.(*APIHandler).handleError
	/go/src/github.com/signoz/signoz/pkg/query-service/app/http_handler.go:1835
go.signoz.io/query-service/app.(*APIHandler).getSpanFilters
	/go/src/github.com/signoz/signoz/pkg/query-service/app/http_handler.go:1276
go.signoz.io/query-service/app.ViewAccess.func1
	/go/src/github.com/signoz/signoz/pkg/query-service/app/http_handler.go:224
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
go.signoz.io/query-service/app.loggingMiddleware.func1
	/go/src/github.com/signoz/signoz/pkg/query-service/app/server.go:187
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
go.signoz.io/query-service/app.(*Server).analyticsMiddleware.func1
	/go/src/github.com/signoz/signoz/pkg/query-service/app/server.go:226
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
go.signoz.io/query-service/app.setTimeoutMiddleware.func1
	/go/src/github.com/signoz/signoz/pkg/query-service/app/server.go:243
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210
github.com/rs/cors.(*Cors).Handler.func1
	/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
github.com/gorilla/handlers.CompressHandlerLevel.func1
	/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:141
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2879
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1930
```
and database signoz_traces is really empty. CH version:
```
ClickHouse server version 22.3.6 revision 54455
```

**Comment by ksponomarev** [comment]
and also this
```
2022-08-03T08:16:47.073Z	error	clickhousetracesexporter/writer.go:100	Could not write a batch of spans	{"kind": "exporter", "name": "clickhousetraces", "error": "code: 60, message: Table signoz_traces.signoz_spans doesn't exist"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhousetracesexporter.(*SpanWriter).backgroundWriter
	/src/exporter/clickhousetracesexporter/writer.go:100
```

**Comment by srikanthccv** [comment]
That shouldn't be the case. Are you sure your collector service up and able to run migrations successfully?

**Comment by ksponomarev** [comment]
No. Still have this error
```
clickhousetracesexporter/clickhouse_factory.go:94	Clickhouse Migrate finished	{"kind": "exporter", "name": "clickhousetraces", "error": "Dirty database version 6. Fix and force version."}
```

**Comment by ksponomarev** [comment]
UPDATE:
I dropped CH at all and reinstalled it. Now apps is working. Thx
