### ISSUE TITLE
Trace page error (URI malformed)

### ISSUE THREAD

**Issue by oneart-dev** [SigNoz/signoz#1612]
## Bug description

After attaching my zap logger(GO 1.19) to telemetry I can't open trace page. Its just blank page with error in console:

Page uri: ```http://localhost:3301/trace/96c0984483049c9134e334727313ee2e?spanId=2d69a0700c7b42cd```
```JS:
main.7b0e755f09d6e677c150.js:2 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at TraceDetail Page.bd7b85fceafe4ecc27a9.js:2:74311
    at Array.map (<anonymous>)
    at TraceDetail Page.bd7b85fceafe4ecc27a9.js:2:74276
    at Array.forEach (<anonymous>)
    at f (TraceDetail Page.bd7b85fceafe4ecc27a9.js:2:74073)
    at k (TraceDetail Page.bd7b85fceafe4ecc27a9.js:2:52816)
    at Da (main.7b0e755f09d6e677c150.js:2:1994294)
    at Ms (main.7b0e755f09d6e677c150.js:2:2046411)
    at iu (main.7b0e755f09d6e677c150.js:2:2033648)
```

Trace without attached logs works just fine.

## Expected behavior
No error

## How to reproduce
```GO
otelLogger = otelzap.New(zapLogger, otelzap.WithMinLevel(zapcore.InfoLevel))
ex.log.Ctx(ex.ctx).Infof("Starting downloading history. Tickers: %d", len(tickers))
ex.log.Ctx(ex.ctx).Debugf("All workers spawned. Wait for completion")
```

## Version information 
* **Signoz version**: Latest
* **Browser version**: Chrome 105.0.5195.125 (Official Build) (arm64)
* **Your OS and version**: Mac os 12.6
* **Your CPU Architecture**(ARM/Intel): ARM

## Additional context
SigNov working in docker droplet. No other issues found so far.
The trace should contain at least 2 levels with 3 spans in my case.

**Comment by ankitnayan** [comment]
@makeavish can you try to reproduce the issue and check what's wrong

**Comment by oneart-dev** [comment]
Server response when opening the corrupted trace:
<details>
<summary>JSON Response</summary>

```JSON
{
  "columns": [
    "__time",
    "SpanId",
    "TraceId",
    "ServiceName",
    "Name",
    "Kind",
    "DurationNano",
    "TagsKeys",
    "TagsValues",
    "References",
    "Events",
    "HasError"
  ],
  "events": [
    [
      1664993463644,
      "22d02521dbb2cfa7",
      "26de7c6971f21afe60709266af7545c7",
      "ws:serve",
      "trade-history",
      "1",
      "22107776958",
      [
        "service.name",
        "library.language"
      ],
      [
        "ws:serve",
        "go"
      ],
      [
        "{TraceId=26de7c6971f21afe60709266af7545c7, SpanId=d3f7e865006efd90, RefType=CHILD_OF}"
      ],
      [],
      false
    ],
    [
      1664993485933,
      "fa54e74d316f5f3f",
      "26de7c6971f21afe60709266af7545c7",
      "ws:serve",
      "balance-history",
      "1",
      "281873125",
      [
        "library.language",
        "service.name"
      ],
      [
        "go",
        "ws:serve"
      ],
      [
        "{TraceId=26de7c6971f21afe60709266af7545c7, SpanId=d3f7e865006efd90, RefType=CHILD_OF}"
      ],
      [],
      false
    ],
    [
      1664993463319,
      "d3f7e865006efd90",
      "26de7c6971f21afe60709266af7545c7",
      "ws:serve",
      "api-key-connection",
      "1",
      "22973988125",
      [
        "ExchangeID",
        "apiKeyID",
        "library.language",
        "service.name"
      ],
      [
        "1",
        "3",
        "go",
        "ws:serve"
      ],
      [
        "{TraceId=26de7c6971f21afe60709266af7545c7, SpanId=, RefType=CHILD_OF}"
      ],
      [
        "{\"name\":\"log\",\"timeUnixNano\":1664993463644243000,\"attributeMap\":{\"code.filepath\":\"/private/var/path/to/file/hidden.go\",\"code.function\":\"github.com/path/hidden/client.(*BinanceFuturesClient).TickersTradeHistory\",\"code.lineno\":\"381\",\"log.message\":\"Starting downloading history. Tickers: 189\",\"log.severity\":\"INFO\",\"log.template\":\"Starting downloading trade history. Tickers: %d\"}}"
      ],
      false
    ]
  ]
}
```
</details>

Hope it helps
