### ISSUE TITLE
Handle misconfigured clickhouse URL at otel-collector

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#1639]
Currently, if the URL of clickhouse is incorrect, the otel-collectors seg fault with below error
```
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x343dd12] goroutine 87 [running]: github.com/SigNoz/signoz-otel-collector/exporter/clickhousemetricsexporter.(*PrwExporter).export.func1() /src/exporter/clickhousemetricsexporter/exporter.go:280 +0xf2 created by github.com/SigNoz/signoz-otel-collector/exporter/clickhousemetricsexporter.(*PrwExporter).export /src/exporter/clickhousemetricsexporter/exporter.go:276 +0x256
```
All the custom exporters should handle this error and show correct log to help user understand the issue better

**Comment by srikanthccv** [comment]
I believe this is done.
