### ISSUE TITLE
'Something went wrong' - invalid memory address or nil pointer dereference goroutine

### ISSUE THREAD

**Issue by geemark** [SigNoz/signoz#1685]
## Bug description

"Something went wrong" message on Service dashboard in the "Rate (ops/s)" and "Error Percentage" chart panels.

![signoz-ui-error](https://user-images.githubusercontent.com/15648549/199814904-747ddff4-7785-4780-919a-f6470096c197.png)

## Expected behavior
Expected the charts to show.

## How to reproduce
Don't know. It happens to about half my services, but works on the others.

## Version information 
* **Signoz version**: 0.11.2
* **Browser version**: Firefox 106
* **Your OS and version**: Windows 11 Pro
* **Your CPU Architecture**(ARM/Intel): Intel Core i7 64bit

## Additional context
I tried digging in the pod logs, and found this in the query service around the time I reload the UI page:
```sh
**"http: panic serving 10.244.0.236:46738: runtime error: invalid memory address or nil pointer dereference goroutine" **


2022-11-03T19:17:30.730Z	[34mINFO[0m	app/server.go:221	/api/v1/service/top_level_operations	timeTaken: 48.77619ms
2022-11-03T19:17:30.770Z	[35mDEBUG[0m	clickhouseReader/reader.go:1663	
		SELECT
			quantile(0.5)(durationNano) as p50,
			quantile(0.95)(durationNano) as p95,
			quantile(0.99)(durationNano) as p99,
			COUNT(*) as numCalls,
			name
		FROM signoz_traces.signoz_index_v2
		WHERE serviceName = @serviceName AND timestamp>= @start AND timestamp<= @end GROUP BY name ORDER BY p99 DESC LIMIT 10
2022-11-03T19:17:30.771Z	[34mINFO[0m	app/server.go:221	/api/v1/service/top_operations	timeTaken: 94.04537ms
2022-11-03T19:17:30.776Z	[35mDEBUG[0m	clickhouseReader/reader.go:849	
		SELECT
			toStartOfInterval(timestamp, INTERVAL @interval minute) as time,
			quantile(0.99)(durationNano) as p99,
			quantile(0.95)(durationNano) as p95,
			quantile(0.50)(durationNano) as p50,
			count(*) as numCalls
		FROM signoz_traces.signoz_index_v2
		WHERE serviceName = @serviceName AND name In [@names] AND timestamp>= @start AND timestamp<= @end GROUP BY time ORDER BY time DESC
2022-11-03T19:17:30.808Z	[35mDEBUG[0m	clickhouseReader/reader.go:875	
		SELECT
			toStartOfInterval(timestamp, INTERVAL @interval minute) as time,
			count(*) as numErrors
		FROM signoz_traces.signoz_index_v2
		WHERE serviceName = @serviceName AND name In [@names] AND timestamp>= @start AND timestamp<= @end AND statusCode=2 GROUP BY time ORDER BY time DESC
2022-11-03T19:17:30.809Z	[34mINFO[0m	app/server.go:221	/api/v1/service/overview	timeTaken: 132.539344ms
2022-11-03T19:17:31.153Z	[31mERROR[0m	app/http_handler.go:1105	query was canceled in query queue
go.signoz.io/signoz/pkg/query-service/app.(*APIHandler).queryRangeMetrics
	/go/src/github.com/signoz/signoz/pkg/query-service/app/http_handler.go:1105
go.signoz.io/signoz/pkg/query-service/app.ViewAccess.func1
	/go/src/github.com/signoz/signoz/pkg/query-service/app/http_handler.go:248
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
go.signoz.io/signoz/ee/query-service/app.loggingMiddleware.func1
	/go/src/github.com/signoz/signoz/ee/query-service/app/server.go:220
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
go.signoz.io/signoz/ee/query-service/app.(*Server).analyticsMiddleware.func1
	/go/src/github.com/signoz/signoz/ee/query-service/app/server.go:264
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
go.signoz.io/signoz/ee/query-service/app.setTimeoutMiddleware.func1
	/go/src/github.com/signoz/signoz/ee/query-service/app/server.go:287
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210
github.com/rs/cors.(*Cors).Handler.func1
	/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
github.com/gorilla/handlers.CompressHandlerLevel.func1
	/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:141
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2047
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2879
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1930
2022/11/03 19:17:31 http: superfluous response.WriteHeader call from github.com/gorilla/handlers.(*compressResponseWriter).WriteHeader (compress.go:26)
2022/11/03 19:17:31 http: panic serving 10.244.0.236:46738: runtime error: invalid memory address or nil pointer dereference
goroutine 347170 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x1ae4fe0, 0x2dd2a70})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
go.signoz.io/signoz/pkg/query-service/app.(*APIHandler).queryRangeMetrics(0xc00015f010, {0x2100bb8, 0xc000688fc0}, 0xc000e22300)
	/go/src/github.com/signoz/signoz/pkg/query-service/app/http_handler.go:1119 +0x39c
go.signoz.io/signoz/pkg/query-service/app.ViewAccess.func1({0x2100bb8, 0xc000688fc0}, 0x48cab7)
	/go/src/github.com/signoz/signoz/pkg/query-service/app/http_handler.go:248 +0x104
net/http.HandlerFunc.ServeHTTP(0x199a580, {0x2100bb8, 0xc000688fc0}, 0xc000e49458)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
go.signoz.io/signoz/ee/query-service/app.loggingMiddleware.func1({0x2100bb8, 0xc000688fc0}, 0x1eea701)
	/go/src/github.com/signoz/signoz/ee/query-service/app/server.go:220 +0xca
net/http.HandlerFunc.ServeHTTP(0x0, {0x2100bb8, 0xc000688fc0}, 0xc0041dcaf0)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
go.signoz.io/signoz/ee/query-service/app.(*Server).analyticsMiddleware.func1({0x21091c8, 0xc0041dcaa0}, 0xdf8475801)
	/go/src/github.com/signoz/signoz/ee/query-service/app/server.go:264 +0xf3
net/http.HandlerFunc.ServeHTTP(0x2113480, {0x21091c8, 0xc0041dcaa0}, 0x13)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
go.signoz.io/signoz/ee/query-service/app.setTimeoutMiddleware.func1({0x21091c8, 0xc0041dcaa0}, 0xc000e22200)
	/go/src/github.com/signoz/signoz/ee/query-service/app/server.go:287 +0x2f6
net/http.HandlerFunc.ServeHTTP(0xc000e22100, {0x21091c8, 0xc0041dcaa0}, 0x71d801)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001ba240, {0x21091c8, 0xc0041dcaa0}, 0xc000e22000)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/rs/cors.(*Cors).Handler.func1({0x21091c8, 0xc0041dcaa0}, 0xc000e22000)
	/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0x0, {0x21091c8, 0xc0041dcaa0}, 0xc000b900d0)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/gorilla/handlers.CompressHandlerLevel.func1({0x21080e8, 0xc000818c40}, 0xc000e22000)
	/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:141 +0x666
net/http.HandlerFunc.ServeHTTP(0xc00025a418, {0x21080e8, 0xc000818c40}, 0x468e4e)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.serverHandler.ServeHTTP({0xc005d45e60}, {0x21080e8, 0xc000818c40}, 0xc000e22000)
	/usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc003b08820, {0x2113480, 0xc000880db0})
	/usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0x4e8
2022-11-03T19:17:39.832Z	[34mINFO[0m	app/server.go:221	/api/v1/version	timeTaken: 23.711µs
```

**Comment by pranay01** [comment]
@geemark Can you share what type of infra are you running SIgNoz on? Is it on docker or k8s? What's the OS of machine where you run SigNoz?

**Comment by geemark** [comment]
K8S install performed using your Helm charts with no customization, on self-managed cluster.
Ubuntu 20.04.5 LTS running on a single AWS EC2 instance.

**Comment by ankitnayan** [comment]
@srikanthccv this is the metrics API failing. How to debug this?

**Comment by srikanthccv** [comment]
Some clear reproducible steps will help. Author says it's not an issue in general and only issue with some services. Was it because something from ClickHouse? or with the query statement? or something else. We could prevent full panic but it would be important to understand what is that exception case which triggers it.

**Comment by pranay01** [comment]
@geemark This issue should be solve with https://github.com/SigNoz/signoz/releases/tag/v0.13.0

feel free to re-open the issue if you see this persist in the above version also
