### ISSUE TITLE
unable to access dashboard

### ISSUE THREAD

**Issue by wailoktam** [SigNoz/signoz#2144]
I get the relevant containers running after installation
7bcdd8271aea   signoz/frontend:0.14.0                       "nginx -g 'daemon of…"   4 days ago       Up 13 minutes             80/tcp, 0.0.0.0:3301->3301/tcp                                                     frontend
e1ecf19ff825   signoz/alertmanager:0.23.0-0.2               "/bin/alertmanager -…"   4 days ago       Up 13 minutes             9093/tcp                                                                           clickhouse-setup-alertmanager-1
9f95130f7df9   signoz/query-service:0.14.0                  "./query-service -co…"   4 days ago       Up 13 minutes (healthy)   8080/tcp                                                                           query-service
c9ce936937f5   signoz/signoz-otel-collector:0.66.2          "/signoz-collector -…"   4 days ago       Up 8 seconds              4317-4318/tcp                                                                      clickhouse-setup-otel-collector-metrics-1
a06203b03e44   clickhouse/clickhouse-server:22.8.8-alpine   "/entrypoint.sh"         4 days ago       Up 13 minutes (healthy)   0.0.0.0:8123->8123/tcp, 0.0.0.0:9000->9000/tcp, 0.0.0.0:9181->9181/tcp, 9009/tcp   clickhouse

But all I get when inputing localhost:3301 is "not found". Anything I am doing wrong?

**Comment by prashant-shahi** [comment]
@wailoktam Can you makes sure that `query-service` is up and running?

You should see SigNoz version when you visit: http://localhost:3301/api/v1/version

**Comment by wailoktam** [comment]
Thanks. My previous problem is solved. I think it was due to my docker desktop is not running. Now I have a different problem. I try the quick start. Get a flask web server running. But when I curl it. I get the following error:

Exception while exporting Span batch.
Traceback (most recent call last):
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd93c0cf310>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/opentelemetry/instrumentation/urllib3/__init__.py", line 187, in instrumented_urlopen
    return wrapped(*args, **kwargs)
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='%3cip%20of%20signoz%20backend%3e', port=4318): Max retries exceeded with url: /v1/traces (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd93c0cf310>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/opentelemetry/sdk/trace/export/__init__.py", line 373, in _export_batch
    self.span_exporter.export(self.spans_list[:idx])  # type: ignore
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 153, in export
    resp = self._export(serialized_data)
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 124, in _export
    return self._session.post(
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/opentelemetry/instrumentation/requests/__init__.py", line 128, in instrumented_request
    return _instrumented_requests_call(
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/opentelemetry/instrumentation/requests/__init__.py", line 159, in _instrumented_requests_call
    return call_wrapped()
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/opentelemetry/instrumentation/requests/__init__.py", line 126, in call_wrapped
    return wrapped_request(self, method, url, *args, **kwargs)
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/opentelemetry/instrumentation/requests/__init__.py", line 148, in instrumented_send
    return _instrumented_requests_call(
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/opentelemetry/instrumentation/requests/__init__.py", line 159, in _instrumented_requests_call
    return call_wrapped()
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/opentelemetry/instrumentation/requests/__init__.py", line 146, in call_wrapped
    return wrapped_send(self, request, **kwargs)
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/wailoktam/otel-getting-started/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='%3cip%20of%20signoz%20backend%3e', port=4318): Max retries exceeded with url: /v1/traces (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd93c0cf310>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by srikanthccv** [comment]
`<IP of SigNoz Backend>` is a placeholder and meant to be replaced with a real host, but it seems you didn't do that. Please use the correct host https://signoz.io/docs/faqs/instrumentation/#i-am-confused-about-ip-of-signoz-can-you-provide-some-examples

**Comment by wailoktam** [comment]
Hi, sorry for the careless mistake. Now I do without the error. But after I curl the web server. I dont get anything shown up in the dashboard visible in browser at localhost:3301. What am I missing? Thanks. Everything is empty

**Comment by srikanthccv** [comment]
It doesn't immediately show up. There will be a small amount of delay. If nothing shows up even after that, it's strange because you had an issue when it tried exporting the data previously. Please share the getting started app repro you are using to test this.

**Comment by wailoktam** [comment]
This is the page I am following: 

https://signoz.io/docs/install/docker/

I use the docker compose method. My enironment is windows 10.  Aftering installing signoz, I create  virtual environment and run:

opentelemetry-bootstrap

Then I run the following

OTEL_RESOURCE_ATTRIBUTES=service.name=otel-getting-started OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4318"  opentelemetry-instrument --traces_exporter otlp_proto_http --metrics_exporter otlp_proto_http python3 /mnt/c/Users/wailok.tam/PycharmProjects/pythonProject/app.py


app.py looks like this:

from random import randint
from flask import Flask, request

app = Flask(__name__)

@app.route("/rolldice")
def roll_dice():
    return str(do_roll())

def do_roll():
    return randint(1, 6)


if __name__== '__main__':
    app.run(host='0.0.0.0', port=5000)

I have no problem curling it.

**Comment by srikanthccv** [comment]
SigNoz doesn't support Windows (yet). You may want to try it on WSL, but I would suggest running Linux. Closing this since your original issues are fixed. Please keep an eye on https://github.com/SigNoz/signoz/issues/2028.
