### ISSUE TITLE
Query Service concurrent map writes

### ISSUE THREAD

**Issue by wfhartford** [SigNoz/signoz#2596]
## Bug description

The query service fails due to concurrent map writes.

## How to reproduce

I'm not sure of exact reproduction scenario, but I believe it's related to viewing large dashboards with many metric graphs.

## Version information 
* **Signoz version**: 0.18.1
* **Browser version**: Firefox 112.0
* **Your OS and version**: Linux Pop_OS! 22.04 LTS
* **Your CPU Architecture**(ARM/Intel): Intel

## Additional context

Partial log excerpt:
```
fatal error: concurrent map writes

goroutine 1016 [running]:
runtime.throw({0x14ee399?, 0x199?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00546d070 sp=0xc00546d040 pc=0x43a731
runtime.mapassign_faststr(0xc000488000?, 0xc000488240?, {0x14eb0c2, 0x13})
	/usr/local/go/src/runtime/map_faststr.go:212 +0x39c fp=0xc00546d0d8 sp=0xc00546d070 pc=0x4155fc
go.signoz.io/signoz/pkg/query-service/telemetry.(*Telemetry).SendEvent(0xc0000f6420, {0x14eb0c2, 0x13}, 0xa?, {0xc00546d337?, 0x12fa220?, 0xc0003ed358?})
	/go/src/github.com/signoz/signoz/pkg/query-service/telemetry/telemetry.go:312 +0x18e fp=0xc00546d2f8 sp=0xc00546d0d8 pc=0xedbace
go.signoz.io/signoz/ee/query-service/app.extractDashboardMetaData({0x14f6ad6, 0x1b}, 0xc00183d600)
	/go/src/github.com/signoz/signoz/ee/query-service/app/server.go:353 +0x36c fp=0xc00546d390 sp=0xc00546d2f8 pc=0x10e34ac
go.signoz.io/signoz/ee/query-service/app.(*Server).analyticsMiddleware.func1({0x18f6160?, 0xc0007b7aa0}, 0xdf8475801?)
	/go/src/github.com/signoz/signoz/ee/query-service/app/server.go:378 +0xa5 fp=0xc00546d698 sp=0xc00546d390 pc=0x10e3785
net/http.HandlerFunc.ServeHTTP(0x18f6518?, {0x18f6160?, 0xc0007b7aa0?}, 0x1b?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc00546d6c0 sp=0xc00546d698 pc=0x6ee78f
go.signoz.io/signoz/ee/query-service/app.setTimeoutMiddleware.func1({0x18f6160, 0xc0007b7aa0}, 0xc00183d500)
	/go/src/github.com/signoz/signoz/ee/query-service/app/server.go:410 +0x2f6 fp=0xc00546d748 sp=0xc00546d6c0 pc=0x10e3f36
net/http.HandlerFunc.ServeHTTP(0xc00183d400?, {0x18f6160?, 0xc0007b7aa0?}, 0xc000a0d610?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc00546d770 sp=0xc00546d748 pc=0x6ee78f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0009500c0, {0x18f6160, 0xc0007b7aa0}, 0xc00183d300)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf fp=0xc00546d898 sp=0xc00546d770 pc=0x77a22f
github.com/rs/cors.(*Cors).Handler.func1({0x18f6160, 0xc0007b7aa0}, 0xc00183d300)
	/go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231 +0x1c4 fp=0xc00546d8f0 sp=0xc00546d898 pc=0x7aeb04
net/http.HandlerFunc.ServeHTTP(0x0?, {0x18f6160?, 0xc0007b7aa0?}, 0xc000a0d5e0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc00546d918 sp=0xc00546d8f0 pc=0x6ee78f
github.com/gorilla/handlers.CompressHandlerLevel.func1({0x18f5200?, 0xc00094c1c0}, 0xc00183d300)
	/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:141 +0x663 fp=0xc00546da70 sp=0xc00546d918 pc=0x779103
net/http.HandlerFunc.ServeHTTP(0x0?, {0x18f5200?, 0xc00094c1c0?}, 0x40f645?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f fp=0xc00546da98 sp=0xc00546da70 pc=0x6ee78f
net/http.serverHandler.ServeHTTP({0x18f0dd0?}, {0x18f5200, 0xc00094c1c0}, 0xc00183d300)
	/usr/local/go/src/net/http/server.go:2916 +0x43b fp=0xc00546db58 sp=0xc00546da98 pc=0x6f1d7b
net/http.(*conn).serve(0xc0000d0b40, {0x18f6518, 0xc0006563c0})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7 fp=0xc00546dfb8 sp=0xc00546db58 pc=0x6ed237
net/http.(*Server).Serve.func3()
	/usr/local/go/src/net/http/server.go:3071 +0x2e fp=0xc00546dfe0 sp=0xc00546dfb8 pc=0x6f26ce
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00546dfe8 sp=0xc00546dfe0 pc=0x46d881
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db
```
Full log file of failure: [signoz-query-service-concurrent-map-write.log](https://github.com/SigNoz/signoz/files/11275937/signoz-query-service-concurrent-map-write.log)

**Comment by wfhartford** [comment]
This occurs for me a few times an hour when using auto-refresh on a large dashboard. My dashborad has 12 different graphs, most of which are plotting data from a handful of series.
