### ISSUE TITLE
Installation Fails with Docker

### ISSUE THREAD

**Issue by SirFitz** [SigNoz/signoz#6031]
## Bug description

Following the installation instructions for docker:
- cloning the repo and going to the deploy folder
- running the docker compose command

Any help would be appreciated in getting this resolved

## Expected behavior
- Signoz is installed and ready to be viewed

## How to reproduce

1. clone the repo
2. navigate to the deploy folder
3. run docker compose up command (https://signoz.io/docs/install/docker/)

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel): 

## Additional context

Error Logs:

```root@ubuntu-4gb-ash-1:~/signoz/deploy# ./install.sh

👋 Thank you for trying out SigNoz!

🌏 Detecting your OS ...

🐳 Starting Docker ...



🟡 Pulling the latest container images for SigNoz.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
           ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
             ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'
🔴 The containers didn't seem to start correctly. Please run the following command to check containers that may have errored out:
```

**Comment by prashant-shahi** [comment]
@SirFitz can you try running the following command?

```bash
cd signoz/deploy
sudo docker compose -f docker/clickhouse-setup/docker-compose.yaml up -d
```

**Comment by prashant-shahi** [comment]
I meant to say, use `docker compose` which comes bundled with Docker instead of standalone `docker-compose`.

Also, can you please share docker and docker compose version?

```bash
sudo docker version
docker compose version
docker-compose version
```

**Comment by SirFitz** [comment]
Okay, I was not able to run the command as it was unavailable in my docker version. 
These are the output of the commands:

```sh
root@ubuntu-4gb-ash-1:~# sudo docker version
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.22.2
 Git commit:        24.0.7-0ubuntu4.1
 Built:             Fri Aug  9 02:33:20 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.22.2
  Git commit:       24.0.7-0ubuntu4.1
  Built:            Fri Aug  9 02:33:20 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.12
  GitCommit:
 runc:
  Version:          1.1.12-0ubuntu3.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
  
  
  
root@ubuntu-4gb-ash-1:~# docker compose version
docker: 'compose' is not a docker command.
See 'docker --help'



root@ubuntu-4gb-ash-1:~# docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.12.3
OpenSSL version: OpenSSL 3.0.13 30 Jan 2024
```


I went to the docker website and updated my version as per the instructions here (https://docs.docker.com/engine/install/ubuntu/)

The result was the containers are now up and running and I'm able to access the Web UI:
<img width="1418" alt="Screenshot 2024-09-20 at 3 05 45 PM" src="https://github.com/user-attachments/assets/91a130ad-022f-41c3-af2e-1b6cb2e786cc">


Thanks a lot for your help!

**Comment by prashant-shahi** [comment]
Thanks for sharing these.

The latest Docker release `v27.3.1` consists of the compose 2.29.7 which has the fixes.

Alternatively, you can get rid of the old `docker-compose` and re-install the latest using `install.sh` script:

```
rm /usr/local/bin/docker-compose /usr/bin/docker-compose

./install.sh
```

Refs:
- https://github.com/moby/moby/releases/tag/v27.3.1
- https://github.com/docker/compose/releases/tag/v2.29.7

**Comment by AleksPish** [comment]
Just want to say thanks for the info in this thread. Was getting the same error when using the usual docker-compose commands after going through my usual process to setup and install docker on a new server. Docker must have made some changes to break the docker-compose on new installs. docker compose now works fine. cheers
